data_dir: data
url: https://evenements.lafranceinsoumise.fr
kramdown:
   input: GFM
   hard_wrap: false
gems:
  - jekyll-seo-tag

twitter:
  username: FranceInsoumise
facebook:
  publisher: https://www.facebook.com/lafranceinsoumise/

social:
  name: La France insoumise
  links:
    - https://www.facebook.com/lafranceinsoumise/
    - https://twitter.com/franceinsoumise

lang: fr_FR

collections:
  evenements:
    output: true
